name: parent_app
publish_to: 'none'
description: Tarteel parent companion app
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  cloud_firestore: ^5.6.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  socket_io_client: ^2.0.3+1
  http: ^1.2.2
  collection: ^1.18.0
  url_launcher: ^6.2.6
  flutter_webrtc: ^0.12.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
flutter_launcher_icons: ^0.14.1
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  remove_alpha_ios: true
